// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEM-u6b5L47KaibBFMxLyd7t-7Dubx43A',
    appId: '1:1069005278575:web:e672f549bd81ae5b262c9a',
    messagingSenderId: '1069005278575',
    projectId: 'readingclub-c1da4',
    authDomain: 'readingclub-c1da4.firebaseapp.com',
    storageBucket: 'readingclub-c1da4.appspot.com',
    measurementId: 'G-SY0LZY1Z9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWG9bxl5CsdSSiaDQfGtb0fzOPXenk1E0',
    appId: '1:1069005278575:android:8d34e941f53cfb8a262c9a',
    messagingSenderId: '1069005278575',
    projectId: 'readingclub-c1da4',
    storageBucket: 'readingclub-c1da4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzppwIUslbSv3A4GtJr8OtEiF8dfMaDUQ',
    appId: '1:1069005278575:ios:3187cdfce762aedc262c9a',
    messagingSenderId: '1069005278575',
    projectId: 'readingclub-c1da4',
    storageBucket: 'readingclub-c1da4.appspot.com',
    iosBundleId: 'com.example.readingclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzppwIUslbSv3A4GtJr8OtEiF8dfMaDUQ',
    appId: '1:1069005278575:ios:f732c922723a0e50262c9a',
    messagingSenderId: '1069005278575',
    projectId: 'readingclub-c1da4',
    storageBucket: 'readingclub-c1da4.appspot.com',
    iosBundleId: 'com.example.readingclub.RunnerTests',
  );
}
